Nprocs: 11 # Multiproceessing option: The number of processors to devote to the healvis simulation of zeroth-order (non-coupled) data.
Nskies: 1  # Keep as 1 for now. See healvis documentation for more details.
do_horizon_taper: true # Taper healpix pixels which are being simulated at the boundary of your field of view. See healvis documentation for more details.
freq:
  start_freq: 144000000 #[Hz]
  end_freq: 159000000
  Nfreqs: 61
time:
  start_time: 2459122.42 # Unit: JD. Start date of 'Galactic Set' datasets used in Paper: 2459122.41130618 
  end_time: 2459122.48 # End date of 'Galactic Set' datasets used in Paper: 2459122.51409459
  Ntimes: 70 # 230
filing:
  outfile_prefix: hv   # Can be changed to your liking.
  outdir: /home/atj/anaconda3/envs/repoCRF/lib/python3.9/site-packages/CoupledRadioInterferometer/Data/2459122/
  clobber: true
  format: uvh5
  outfile_suffix: GLEAM_RUBY_FOV179_NTIMES70_Nbls0_GALACTIC_SET
skyparam:
  sky_type: /home/atj/anaconda3/envs/repoCRF/lib/python3.9/site-packages/CoupledRadioInterferometer/Sky_Models/GLEAM_v2_Ruby_Nside128_144-169MHz_101Nfreqs.hdf5
  Nside: 128
  Nskies: 1 # Keep as 1 for now. See healvis documentation for more details.
telescope:
  telescope_location: (-30.72152777777791, 21.428305555555557, 1073.0000000093132)
  array_layout: /home/atj/anaconda3/envs/repoCRF/lib/python3.9/site-packages/CoupledRadioInterferometer/Array_Configurations/HERA_JD_2459122_demo.csv                         #needn't be JD specific if antenna_nums is in 'select'
  telescope_name: HERA
  redundancy: 1.0
beam:
  beam_type: /home/atj/anaconda3/envs/repoCRF/lib/python3.9/site-packages/CoupledRadioInterferometer/Beams/airy_analytic_power_beam_240_Nfreqs_64_nside_healpix_v2.fits
  pols:
  - xx     # This polarization code should be in the UVBeam object you use, and also be consistent with an electromagnetic simulation output (e.g. CST)
  smooth_beam: false # See healvis documentation for more details.
  beam_freq_interp: nearest   # While it is set to 'nearest', no interpolation is done if all frequencies of your simulation (e.g. 'start_freq -> end_freq') are also found in the UVBeam object.
  fov: 179 # [deg.], where 180 deg. corresponds to the horizon. See healvis documentation for more details.Set to <180 if using airy disk beam
select:
  no_autos: false #To include or not include autocorrelation data in the healivis simulation. To calculate first-order coupling, we need autocorrs. 
  make_full: false # since complete_uvdata(uv_obj) is already run in the 'run_simulation()' function of healvis' 'simulator.py' script
